### ISSUE TITLE
rocksdb crashed

### ISSUE THREAD

**Issue by egonspace** [line/lfb-sdk#321]
## Summary of Bug
lfb node was crashed with following stack trace.
`signal SIGBUS: bus error code=0x4` means 
```
/* hardware memory error consumed on a machine check: action required */
#define BUS_MCEERR_AR   4
```
And wiki says `On x86 architectures, a machine-check exception is not caused by software` in https://en.wikipedia.org/wiki/Machine-check_exception.

We need to wait and see if this error occurs again. If it does not occur for a long time, we can ignore this issue.

```
2021/09/08-09:12:24.902 INF received complete proposal block hash=80B67B9352E551110F9D4152544D0AAE1D0466E4663D4EB6369408543FEF9ED0 height=134033 module=consensus
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x4 addr=0x16d53000 pc=0x7f976afb737c]

runtime stack:
runtime.throw(0x219aae4, 0x2a)
	runtime/panic.go:1117 +0x72
runtime.sigpanic()
	runtime/signal_unix.go:718 +0x2e5

goroutine 82039077 [syscall]:
runtime.cgocall(0x1a8b8f9, 0xc008064c10, 0xc01492c3e0)
	runtime/cgocall.go:154 +0x5b fp=0xc008064be0 sp=0xc008064ba8 pc=0x5382db
github.com/line/gorocksdb._Cfunc_rocksdb_get(0x7f972c02bbe0, 0x7f972c02c4c0, 0xc01b2adf60, 0xb, 0xc01b2adf48, 0xc01492c3e0, 0x0)
	_cgo_gotypes.go:1597 +0x49 fp=0xc008064c10 sp=0xc008064be0 pc=0xe50389
github.com/line/gorocksdb.(*DB).GetBytes.func1(0xc0013ffd20, 0xc00003c900, 0xc01b2adf60, 0xc01b2adf60, 0xb, 0x10, 0xc01b2adf48, 0xc01492c3e0, 0xc01b2adf60)
	github.com/line/gorocksdb@v0.0.0-20210406043732-d4bea34b6d55/db.go:262 +0x105 fp=0xc008064c68 sp=0xc008064c10 pc=0xe66b25
github.com/line/gorocksdb.(*DB).GetBytes(0xc0013ffd20, 0xc00003c900, 0xc01b2adf60, 0xb, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/line/gorocksdb@v0.0.0-20210406043732-d4bea34b6d55/db.go:262 +0xf9 fp=0xc008064d00 sp=0xc008064c68 pc=0xe59999
github.com/line/tm-db/v2/rocksdb.(*RocksDB).Get(0xc0013ffd40, 0xc01b2adf60, 0xb, 0x10, 0xb, 0x10, 0xb, 0xc0000, 0xc054cc8000)
	github.com/line/tm-db/v2@v2.0.0-init.1.0.20210413083915-5bb60e117524/rocksdb/db.go:72 +0x9d fp=0xc008064d60 sp=0xc008064d00 pc=0xe7593d
github.com/line/ostracon/store.(*BlockStore).LoadBlockPart(0xc00003c940, 0x20b36, 0xd, 0xc6000)
	github.com/line/ostracon@v0.34.9-0.20210610071151-a52812ac9add/store/store.go:153 +0x131 fp=0xc008064df0 sp=0xc008064d60 pc=0x11c18f1
github.com/line/ostracon/store.(*BlockStore).LoadBlock(0xc00003c940, 0x20b36, 0x20b36)
	github.com/line/ostracon@v0.34.9-0.20210610071151-a52812ac9add/store/store.go:103 +0x10f fp=0xc008064e98 sp=0xc008064df0 pc=0x11c124f
github.com/line/ostracon/rpc/core.Block(0xc0013b9520, 0xc01b2ad968, 0xc0013b9520, 0xc00b4d9080, 0x0)
	github.com/line/ostracon@v0.34.9-0.20210610071151-a52812ac9add/rpc/core/blocks.go:83 +0x90 fp=0xc008064ef0 sp=0xc008064e98 pc=0x12897b0
github.com/line/ostracon/rpc/client/local.(*Local).Block(0xc0013b9500, 0x25dc3e8, 0xc0001221b0, 0xc01b2ad968, 0xc00b4d9080, 0x0, 0x0)
	github.com/line/ostracon@v0.34.9-0.20210610071151-a52812ac9add/rpc/client/local/local.go:157 +0x39 fp=0xc008064f28 sp=0xc008064ef0 pc=0x12c6e99
github.com/line/lfb-sdk/client/grpc/tmservice.getBlock(0x0, 0x0, 0x0, 0x25fe570, 0xc0013b9500, 0x0, 0x0, 0x25e50e8, 0xc001100420, 0x25e8298, ...)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/client/grpc/tmservice/block.go:18 +0xcd fp=0xc0080650b8 sp=0xc008064f28 pc=0x12fa5cd
github.com/line/lfb-sdk/client/grpc/tmservice.queryServer.GetBlockByHeight(0x0, 0x0, 0x0, 0x25fe570, 0xc0013b9500, 0x0, 0x0, 0x25e50e8, 0xc001100420, 0x25e8298, ...)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/client/grpc/tmservice/service.go:78 +0xc5 fp=0xc0080652b8 sp=0xc0080650b8 pc=0x1318aa5
github.com/line/lfb-sdk/client/grpc/tmservice.(*queryServer).GetBlockByHeight(0xc0014118c0, 0x25dc458, 0xc0324e03c0, 0xc01b2ad968, 0xc0014118c0, 0x0, 0xc0001d15f8)
	<autogenerated>:1 +0xc8 fp=0xc008065598 sp=0xc0080652b8 pc=0x131f8c8
github.com/line/lfb-sdk/client/grpc/tmservice._Service_GetBlockByHeight_Handler(0x206b820, 0xc0014118c0, 0x25dc458, 0xc0324e03c0, 0xc01f876e10, 0x0, 0x25dc458, 0xc0324e03c0, 0xa, 0x0)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/client/grpc/tmservice/query.pb.go:1391 +0x214 fp=0xc008065608 sp=0xc008065598 pc=0x1302414
github.com/line/lfb-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1(0x25dc3e8, 0xc0001221b0, 0x25f2708, 0xc01f024100, 0xb, 0x0, 0xc01e4a7bc0, 0xa, 0x20b90, 0xbff5c67, ...)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/baseapp/grpcrouter.go:92 +0x20c fp=0xc008065b10 sp=0xc008065608 pc=0x12f406c
github.com/line/lfb-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc000f44000, 0xc00129dcc0, 0xc01b2ad478, 0x4, 0x4, 0x21b130e, 0x33, 0x20b90, 0x0, 0x0, ...)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/baseapp/abci.go:590 +0x19e fp=0xc008066418 sp=0xc008065b10 pc=0x12e6ade
github.com/line/lfb-sdk/baseapp.(*BaseApp).Query(0xc000f44000, 0xc01b2ad478, 0x4, 0x4, 0x21b130e, 0x33, 0x20b90, 0x0, 0x0, 0x0, ...)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/baseapp/abci.go:434 +0x96f fp=0xc008066700 sp=0xc008066418 pc=0x12e52cf
github.com/line/ostracon/abci/client.(*localClient).QuerySync(0xc0010f0310, 0xc01b2ad478, 0x4, 0x4, 0x21b130e, 0x33, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/line/ostracon@v0.34.9-0.20210610071151-a52812ac9add/abci/client/local_client.go:256 +0x111 fp=0xc008066870 sp=0xc008066700 pc=0xf62871
github.com/line/ostracon/proxy.(*appConnQuery).QuerySync(0xc00048efb0, 0xc01b2ad478, 0x4, 0x4, 0x21b130e, 0x33, 0x0, 0x0, 0x549d5b, 0xc0415de828, ...)
	github.com/line/ostracon@v0.34.9-0.20210610071151-a52812ac9add/proxy/app_conn.go:160 +0x68 fp=0xc0080668d8 sp=0xc008066870 pc=0xfc7968
github.com/line/ostracon/rpc/core.ABCIQuery(0xc0013b9520, 0x21b130e, 0x33, 0xc01b2ad478, 0x4, 0x4, 0x0, 0x0, 0x20a7080, 0xc0013b81c0, ...)
	github.com/line/ostracon@v0.34.9-0.20210610071151-a52812ac9add/rpc/core/abci.go:20 +0x103 fp=0xc008066990 sp=0xc0080668d8 pc=0x1288d43
github.com/line/ostracon/rpc/client/local.(*Local).ABCIQueryWithOptions(0xc0013b9500, 0x25dc3e8, 0xc0001221b0, 0x21b130e, 0x33, 0xc01b2ad478, 0x4, 0x4, 0x0, 0x0, ...)
	github.com/line/ostracon@v0.34.9-0.20210610071151-a52812ac9add/rpc/client/local/local.go:87 +0x8d fp=0xc0080669f8 sp=0xc008066990 pc=0x12c65ed
github.com/line/lfb-sdk/client.Context.queryABCI(0x0, 0x0, 0x0, 0x25fe570, 0xc0013b9500, 0x0, 0x0, 0x25e50e8, 0xc001100420, 0x25e8298, ...)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/client/query.go:76 +0x11c fp=0xc008066c68 sp=0xc0080669f8 pc=0x10e1edc
github.com/line/lfb-sdk/client.Context.QueryABCI(...)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/client/query.go:52
github.com/line/lfb-sdk/client.RunGRPCQuery(0x0, 0x0, 0x0, 0x25fe570, 0xc0013b9500, 0x0, 0x0, 0x25e50e8, 0xc001100420, 0x25e8298, ...)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/client/grpc_query.go:119 +0x278 fp=0xc008067348 sp=0xc008066c68 pc=0x10e12f8
github.com/line/lfb-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func1(0x25dc458, 0xc01fc83740, 0x2094e80, 0xc01b2ad470, 0xc01f9f86a0, 0xc014c7f518, 0xb1d074, 0xc01b2ad470, 0xc01b2ad468, 0x4)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/baseapp/grpcserver.go:41 +0x1b0 fp=0xc008067910 sp=0xc008067348 pc=0x12f4530
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x25dc458, 0xc01fc83740, 0x2094e80, 0xc01b2ad470, 0x2009c80, 0x7f96d4236c08, 0xc008e349e8, 0x7f967c0537f8)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x63 fp=0xc008067970 sp=0xc008067910 pc=0x12e0723
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x25dc458, 0xc01fc83740, 0x2094e80, 0xc01b2ad470, 0xc01f9f86a0, 0xc01f9f86c0, 0x0, 0x0, 0x0, 0x0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:33 +0xcb fp=0xc0080679f8 sp=0xc008067970 pc=0x12e0dab
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x25dc458, 0xc01fc83740, 0x2094e80, 0xc01b2ad470, 0xc001d80400, 0x0, 0xc008e34ab8, 0x542e38)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x63 fp=0xc008067a58 sp=0xc0080679f8 pc=0x12e0723
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x25dc458, 0xc01fc83740, 0x2094e80, 0xc01b2ad470, 0xc01f9f86a0, 0xc014c7f518, 0xc008e34b01, 0xc01fc83770, 0xc008e34b28, 0x12e064d)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xd7 fp=0xc008067ac8 sp=0xc008067a58 pc=0x12e0917
github.com/line/lfb-sdk/client/grpc/tmservice._Service_GetBlockByHeight_Handler(0x206b820, 0xc0014118c0, 0x25dc458, 0xc01fc83740, 0xc034fb2780, 0xc01fc83770, 0xc01fc83740, 0xc008e34ba0, 0x8d8bc6, 0x20395a0)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/client/grpc/tmservice/query.pb.go:1400 +0x150 fp=0xc008067b38 sp=0xc008067ac8 pc=0x1302350
github.com/line/lfb-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2(0x206b820, 0xc0014118c0, 0x25dc458, 0xc01fc83740, 0xc034fb2780, 0x0, 0x25dc458, 0xc01fc83740, 0xc01b2ad468, 0x4)
	github.com/line/lfb-sdk@v1.0.0-init.1.0.20210720072128-577c2c01cf60/baseapp/grpcserver.go:90 +0xf6 fp=0xc008067bb0 sp=0xc008067b38 pc=0x12f49d6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0011d3180, 0x25ee998, 0xc01bfd6c00, 0xc0013ad600, 0xc007a44e70, 0xc0005427c8, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1210 +0x52b fp=0xc008067e50 sp=0xc008067bb0 pc=0xb8678b
google.golang.org/grpc.(*Server).handleStream(0xc0011d3180, 0x25ee998, 0xc01bfd6c00, 0xc0013ad600, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1533 +0xd0c fp=0xc008067f68 sp=0xc008067e50 pc=0xb8a94c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc01eb41c60, 0xc0011d3180, 0x25ee998, 0xc01bfd6c00, 0xc0013ad600)
	google.golang.org/grpc@v1.39.0/server.go:871 +0xab fp=0xc008067fb8 sp=0xc008067f68 pc=0xb97a0b
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc008067fc0 sp=0xc008067fb8 pc=0x5a7021
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.39.0/server.go:869 +0x1fd
```

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by egonspace** [comment]
We confirmed that this problem was caused by a problem with the memory of the PM.
